/**
 * categories.ts - localStorage-Backed Category List
 *
 * Categories are no longer a fixed enum baked into the type system - they
 * are a plain array of Category objects persisted to localStorage, so a
 * user can add their own category at runtime without a code change. This
 * file owns reading/writing that list and generating new categories.
 *
 * Every function here reads the full list, mutates it, and writes it back
 * rather than diffing in place - the list is small (a handful of
 * categories), so treating localStorage as the single source of truth on
 * every call keeps this simple and avoids a separate in-memory cache
 * getting out of sync with what's on disk.
 */

import { Category, DEFAULT_CATEGORIES } from '../types/Category';

/** localStorage key the category list is persisted under. */
const CATEGORIES_STORAGE_KEY = 'dabble-categories';

/**
 * PROCEDURAL CATEGORY COLOR GENERATION (golden-angle hue rotation)
 *
 * New categories used to cycle through a fixed array of hand-picked hex
 * colors (NEW_CATEGORY_COLOR_PALETTE, now removed) - which meant the Nth
 * category beyond the array's length necessarily reused an earlier color.
 * Instead, each new category's hue is the previous category's hue rotated
 * by the golden angle (~137.5deg = 360deg * (1 - 1/phi)). Repeatedly
 * stepping by an irrational fraction of a full turn is the same trick
 * phyllotaxis (sunflower seed heads, pinecones) uses to pack items with
 * maximal separation: successive hues never fall into a short repeating
 * cycle the way a rational step (e.g. 90deg or 120deg) would, so however
 * many categories a user creates - 5 or 500 - each new one lands roughly
 * as far around the color wheel from its neighbors as possible, with no
 * finite list to exhaust or cycle back through.
 *
 * Saturation and lightness are held fixed at values matched to the old
 * palette's own colors (averaging ~85% saturation / ~62% lightness across
 * DEFAULT_CATEGORIES + the old palette - see the HSL readout this was
 * derived from) so generated colors keep the same vivid-pastel look
 * against both the light and dark theme, and only hue varies.
 */
const GOLDEN_ANGLE_DEGREES = 137.5;
const CATEGORY_SATURATION_PERCENT = 85;
const CATEGORY_LIGHTNESS_PERCENT = 62;
/** Hue a brand-new category list (no categories yet) starts rotating from. */
const BASE_HUE_DEGREES = 0;

/** Converts an "#rrggbb" hex color to {h: 0-360, s: 0-100, l: 0-100}. */
function hexToHsl(hex: string): { h: number; s: number; l: number } {
  const r = parseInt(hex.slice(1, 3), 16) / 255;
  const g = parseInt(hex.slice(3, 5), 16) / 255;
  const b = parseInt(hex.slice(5, 7), 16) / 255;

  const max = Math.max(r, g, b);
  const min = Math.min(r, g, b);
  const l = (max + min) / 2;

  if (max === min) {
    return { h: 0, s: 0, l: l * 100 };
  }

  const delta = max - min;
  const s = l > 0.5 ? delta / (2 - max - min) : delta / (max + min);

  let h: number;
  switch (max) {
    case r:
      h = ((g - b) / delta + (g < b ? 6 : 0)) * 60;
      break;
    case g:
      h = ((b - r) / delta + 2) * 60;
      break;
    default:
      h = ((r - g) / delta + 4) * 60;
      break;
  }

  return { h, s: s * 100, l: l * 100 };
}

/** Converts {h: 0-360, s: 0-100, l: 0-100} to an "#rrggbb" hex color. */
function hslToHex(h: number, s: number, l: number): string {
  const sFraction = s / 100;
  const lFraction = l / 100;

  const chroma = (1 - Math.abs(2 * lFraction - 1)) * sFraction;
  const huePrime = h / 60;
  const secondLargest = chroma * (1 - Math.abs((huePrime % 2) - 1));
  const lightnessMatch = lFraction - chroma / 2;

  let rgb: [number, number, number];
  if (huePrime < 1) rgb = [chroma, secondLargest, 0];
  else if (huePrime < 2) rgb = [secondLargest, chroma, 0];
  else if (huePrime < 3) rgb = [0, chroma, secondLargest];
  else if (huePrime < 4) rgb = [0, secondLargest, chroma];
  else if (huePrime < 5) rgb = [secondLargest, 0, chroma];
  else rgb = [chroma, 0, secondLargest];

  const toHexByte = (value: number) =>
    Math.round((value + lightnessMatch) * 255)
      .toString(16)
      .padStart(2, '0');

  return `#${toHexByte(rgb[0])}${toHexByte(rgb[1])}${toHexByte(rgb[2])}`;
}

/**
 * Computes the next hue in the golden-angle sequence, given the existing
 * category list. Rather than persisting a separate "last hue used"
 * counter, the previous hue is derived by reading back the most-recently-
 * added category's own color (the last element of the list, since
 * addCategory always appends) and converting it from hex to HSL - so the
 * sequence keeps advancing correctly even if that category's color was
 * later hand-picked from the override swatch grid (see
 * getCategoryColorOptions) rather than generated by this same function.
 */
function nextCategoryHue(existingCategories: Category[]): number {
  if (existingCategories.length === 0) {
    return BASE_HUE_DEGREES;
  }

  const mostRecentCategory = existingCategories[existingCategories.length - 1];
  const { h: previousHue } = hexToHsl(mostRecentCategory.color);
  return (previousHue + GOLDEN_ANGLE_DEGREES) % 360;
}

/**
 * Loads the category list from localStorage.
 *
 * Falls back to DEFAULT_CATEGORIES when nothing has been saved yet (first
 * run) or when the stored value can't be parsed, so callers always get a
 * usable list back.
 */
export function loadCategories(): Category[] {
  const raw = localStorage.getItem(CATEGORIES_STORAGE_KEY);
  if (!raw) {
    return DEFAULT_CATEGORIES;
  }

  try {
    const parsed = JSON.parse(raw);
    if (Array.isArray(parsed)) {
      return parsed as Category[];
    }
  } catch {
    // Corrupt or unexpected data - fall through to the defaults below.
  }

  return DEFAULT_CATEGORIES;
}

/** Persists the given category list to localStorage. */
export function saveCategories(categories: Category[]): void {
  localStorage.setItem(CATEGORIES_STORAGE_KEY, JSON.stringify(categories));
}

/**
 * Generates the color a new category would get next, by rotating the most
 * recently added category's hue by the golden angle (see the PROCEDURAL
 * CATEGORY COLOR GENERATION comment above). Exported (not just used
 * internally by addCategory) so AddEntryForm's inline "add new category"
 * sub-form can show the color swatch preview before the category is
 * actually created - see previewNextCategoryColor below.
 */
export function pickColorForNewCategory(
  existingCategories: Category[]
): string {
  return hslToHex(
    nextCategoryHue(existingCategories),
    CATEGORY_SATURATION_PERCENT,
    CATEGORY_LIGHTNESS_PERCENT
  );
}

/**
 * Returns `count` alternative colors for a new category, continuing the
 * golden-angle sequence past the default suggestion (index 0 here is the
 * exact same color pickColorForNewCategory/previewNextCategoryColor would
 * pick). Used by AddEntryForm's swatch grid to offer a few more distinct
 * options beyond the default without exposing an arbitrary color
 * picker - each option is still a procedurally generated, well-separated
 * hue, just further along the same rotation.
 */
export function getCategoryColorOptions(
  existingCategories: Category[],
  count: number
): string[] {
  const baseHue = nextCategoryHue(existingCategories);
  return Array.from({ length: count }, (_, index) =>
    hslToHex(
      (baseHue + index * GOLDEN_ANGLE_DEGREES) % 360,
      CATEGORY_SATURATION_PERCENT,
      CATEGORY_LIGHTNESS_PERCENT
    )
  );
}

/**
 * Returns `count` alternative colors generated by rotating away from
 * `baseColor`'s OWN hue by the golden angle, repeatedly - the same
 * well-separated-hue trick pickColorForNewCategory/getCategoryColorOptions
 * use for a brand-new category (see the PROCEDURAL CATEGORY COLOR
 * GENERATION comment above), just anchored to an EXISTING category's own
 * current color instead of "whatever hue comes next in the global
 * new-category sequence". Used by ManageCategoriesModal's expanded color
 * picker to suggest alternatives to a category's own current color that
 * stay visually well-separated from it (index 0 is one golden-angle step
 * away from `baseColor`, never `baseColor` itself).
 */
export function getHueRotatedColorOptions(
  baseColor: string,
  count: number
): string[] {
  const { h: baseHue } = hexToHsl(baseColor);
  return Array.from({ length: count }, (_, index) =>
    hslToHex(
      (baseHue + (index + 1) * GOLDEN_ANGLE_DEGREES) % 360,
      CATEGORY_SATURATION_PERCENT,
      CATEGORY_LIGHTNESS_PERCENT
    )
  );
}

/**
 * Creates a new category with the given name, persists the updated list,
 * and returns the new category.
 *
 * `color` defaults to the next golden-angle color (same as
 * previewNextCategoryColor would show) but can be overridden - e.g. when
 * the user picked an alternative from AddEntryForm's swatch grid (see
 * getCategoryColorOptions) instead of accepting the default suggestion.
 */
export function addCategory(name: string, color?: string): Category {
  const existingCategories = loadCategories();

  const newCategory: Category = {
    id: crypto.randomUUID(),
    name,
    color: color ?? pickColorForNewCategory(existingCategories),
  };

  saveCategories([...existingCategories, newCategory]);

  return newCategory;
}

/**
 * Returns the color a brand-new category would be assigned right now,
 * without actually creating or persisting one.
 *
 * Used by AddEntryForm's inline "add new category" sub-form to show a
 * live swatch preview while the user is still typing a name (and might
 * cancel) - calling addCategory itself there would persist a category to
 * localStorage before the user has confirmed anything.
 */
export function previewNextCategoryColor(): string {
  return pickColorForNewCategory(loadCategories());
}

/**
 * Returns `count` alternative colors for AddEntryForm's swatch-grid
 * override, based on the current category list, without persisting
 * anything. See getCategoryColorOptions.
 */
export function previewCategoryColorOptions(count: number): string[] {
  return getCategoryColorOptions(loadCategories(), count);
}

/**
 * Removes a category from the persisted list by id. Used when deleting the
 * last remaining entry of a category (see AddEntryForm's DELETE ENTRY /
 * ORPHANED-CATEGORY CASCADE comment) - mirrors addCategory's own
 * read-mutate-write pattern. A no-op (silently) if `categoryId` doesn't
 * match any category, rather than throwing.
 *
 * Also records `categoryId` as a tombstone (see loadDeletedCategoryIds
 * below) - necessary for the same reason recordDeletedEntryId is: if this
 * happens to be one of the bundled DEFAULT_CATEGORIES ids,
 * utils/initializeFirstVisit.ts's backfillNewBundledDefaults would
 * otherwise see it "missing" from storage on the very next load and
 * silently re-add it, undoing the delete.
 */
export function deleteCategory(categoryId: string): void {
  const existingCategories = loadCategories();
  saveCategories(
    existingCategories.filter(category => category.id !== categoryId)
  );
  recordDeletedCategoryId(categoryId);
}

/**
 * Renames and/or recolors an existing category in place, by id, preserving
 * every other field (including `domain`). Used by ManageCategoriesModal's
 * per-row name input and color swatch picker.
 *
 * RENAME/RECOLOR NEEDS NO ENTRY DATA CHANGES: an Entry references its
 * category via `activityType`, a stable category id - never a name or
 * color snapshot of its own. So updating a category's `name`/`color` here
 * is the ONLY write needed; every entry that references this category by
 * id picks up the new display name/color the next time it's looked up
 * (getCategoryName/getActivityColor), with zero Entry objects touched.
 */
export function updateCategory(
  categoryId: string,
  updates: Partial<Pick<Category, 'name' | 'color'>>
): void {
  const existingCategories = loadCategories();
  saveCategories(
    existingCategories.map(category =>
      category.id === categoryId ? { ...category, ...updates } : category
    )
  );
}

/**
 * DELETED-CATEGORY TOMBSTONES - see recordDeletedEntryId in
 * entriesStorage.ts for the full reasoning; this is the category-list
 * equivalent, consulted by the same backfillNewBundledDefaults.
 */
const DELETED_CATEGORY_IDS_STORAGE_KEY = 'dabble-deleted-category-ids';

/** Loads the tombstone list of deleted category ids, or [] if none recorded/parseable. */
export function loadDeletedCategoryIds(): string[] {
  const raw = localStorage.getItem(DELETED_CATEGORY_IDS_STORAGE_KEY);
  if (!raw) return [];

  try {
    const parsed = JSON.parse(raw);
    if (Array.isArray(parsed)) {
      return parsed as string[];
    }
  } catch {
    // Corrupt or unexpected data - fall through to the empty array below.
  }

  return [];
}

/** Appends `categoryId` to the tombstone list (a no-op if already recorded). */
function recordDeletedCategoryId(categoryId: string): void {
  const existing = loadDeletedCategoryIds();
  if (existing.includes(categoryId)) return;
  localStorage.setItem(
    DELETED_CATEGORY_IDS_STORAGE_KEY,
    JSON.stringify([...existing, categoryId])
  );
}

/**
 * Looks up a category's display name by id, falling back to the raw id
 * itself if no matching category exists (e.g. its category was deleted).
 * Used anywhere an Entry's activityType needs to be shown as a label
 * rather than compared/looked up for color (see getActivityColor in
 * utils/colors.ts for the color equivalent).
 */
export function getCategoryName(activityType: string): string {
  const category = loadCategories().find(
    candidate =>
      candidate.id === activityType || candidate.name === activityType
  );
  return category?.name ?? activityType;
}
